Streamline GitHub Actions.
Move the build of the manager binary to the unit-tests Prow script.
Remove the linting of the code in favor of the lint Prow script.

diff --git a/ci/prow/lint b/ci/prow/lint
--- a/ci/prow/lint
+++ b/ci/prow/lint
@@ -2,4 +2,14 @@
 
 set -euxo pipefail
 
+# Generate code and compare with the current source.
+# Fail with a diff if some files are outdated.
+go install github.com/golang/mock/mockgen@v1.6.0
+PATH="${PATH}:${GOPATH}/bin" make generate
+
+if ! git diff --exit-code; then
+    echo "Changes detected"
+    exit 1
+fi
+
 make lint
